### ISSUE TITLE
Update API of pinned tags for visitor

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2662]
Team ask a way to setup default pinned tags for visitors, so we might update API for the need.

### Tasks
- [x] Doc for schema changes
- [x] DB: new table
- [ ] API: mutation and query

**Comment by devformatters** [comment]
Issue requires review and rearrangement. Close it.
