### ISSUE TITLE
[Server] User's article list has duplicated articles

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2673]
### Tasks
- [ ] Find the cause of the problem
- [ ] Add possible db-level prevention
- [ ] Remove possible duplication in query result

### References
- [ ] [Slack](https://mattersnews.slack.com/archives/GA0R09FHN/p1660062117191319)
- [ ] [Case 1: user page](https://matters.news/@yujiewu00)
- [ ] [Case 2: user page](https://matters.news/@Ricamoh)
- [ ] [Case 3: user page](https://matters.news/@hi176)

**Comment by devformatters** [comment]
@tx0c I've add more cases to this issue. And Matty also encountered just yesterday.

cc @robertu7

**Comment by tx0c** [comment]
close in #2743
