### ISSUE TITLE
IPNS personal page: index HTML

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2770]
## Goal
Create `index.html` at IPNS root during each publication. It is a readable index for users, and a reference for JSON feed with `<alter link = `.

### Tasks
- [ ] Create a plain personal webpage under each user's IPNS address
- [ ] Each item points to the user's article on Matters.News
- [ ] `<alter link = ` points to `./feed.json`

### References
- [Design](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=7904%3A46005)

Plain personal webpage:
- [Planet](https://olivida.eth.limo/)
- [Vitalik](https://vitalik.eth.limo/)

**Comment by devformatters** [comment]
Close it since we will release it soon. And there are new tasks coming.
