### ISSUE TITLE
IPNS personal page: linking articles on IPFS

### ISSUE THREAD

**Issue by guoliu** [thematters/matters-server#2776]
# Goal
Link articles previously published on IPFS to IPNS, and reference them with relative paths. This allows users to distribute content p2p, and use the IPNS address for their personal page on ENS.

# Tasks
- [ ] Use relative path for articles in `index.html` and `feed.json` (needs a naming convention)
- [ ] After creating `index.html`, link in new and previous articles and get a new root hash
  - [ ] Articles need to be added one by one, see discussion ([1](https://discuss.ipfs.tech/t/how-can-i-wrap-existing-files-in-a-directory-from-the-command-line/7616), [2](https://discuss.ipfs.tech/t/how-can-attach-cid-to-new-node/7534))
- [ ] Pin root hash non-recursively ([doc](https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/PIN.md#options))

# Notes 
Linking CIDs into directories could be highly useful, needs a careful design for the module or API.
