### ISSUE TITLE
Implement APIs for support settings

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2822]
### Tasks
- [ ] API design documentation
- [ ] create APIs for setup
  - Support encouragement quote
  - Thank-you support  message
- [ ] Settings can be update in both
  - Draft settings
  - Published Article settings

### References
- [Product doc](https://paper.dropbox.com/doc/Matters--BqdxffYuRPBH7Ql~Sg7Z8ssWAg-3lhxiAzEnwkCA6SaphWXY)
- [Design](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=6562%3A41913)

### Blocked
- https://github.com/thematters/matters-web/issues/2808

**Comment by gary02** [comment]
https://www.notion.so/matterslab/Support-Setting-431535c4b6484597981d73488ed6b2cd

**Comment by devformatters** [comment]
2
