### ISSUE TITLE
Update API for user to add up 10 connections per article

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#3222]
### Tasks
- [ ] Update API for allowing user to add up 10 connections per article
- [ ] Allow existing article to decrease the number
- [ ] Update test case

### References
- [Design](https://www.figma.com/file/vO8f8jaz9cZo1DsAazvHWd/Matters.news-%E8%BF%AD%E4%BB%A3%E8%AE%BE%E8%AE%A1?t=qez9FjTEBSH7jVT8-0)

**Comment by devformatters** [comment]
@gary02 I've added one task for unit test for this update
