### ISSUE TITLE
Update APIs to restrict new user name in lower case

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#3244]
### Tasks
- [x] Update APIs to restrict new user name in lower case:

  - [x] Registration
  - [x] Change user name

- [x] Update test cases

### References
- [Thread](https://mattersnews.slack.com/archives/G805NQVE3/p1678159872394439)

**Comment by robertu7** [comment]
"restrict" means we will lowercase the username and store it in DB, not throw an error if it contains uppercase letter, right?
