### ISSUE TITLE
Search Service Solution

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#3305]
### Tasks
- [ ] Research integration of PaddleHub & Postgres tsvector
  - [ ] https://github.com/PaddlePaddle/PaddleHub#the-simplest-cases-of-chinese-word-segmentation
  - [ ] https://github.com/PaddlePaddle/Paddle.js
- [ ] Extract segmentations from search plugins

### References

https://github.com/thematters/lambda-handlers/blob/main/sql/create-table-search-index-article.sql#LL30C1-L33C1

currently all tsvector are automatically generated by Postgres with column of `GENERATED ALWAYS AS (to_tsvector('jiebacfg', title)) STORED `
```sql
ALTER TABLE search_index.article ADD COLUMN title_jieba_ts tsvector
  GENERATED ALWAYS AS (to_tsvector('jiebacfg', title)) STORED ;
ALTER TABLE search_index.article ADD COLUMN summary_jieba_ts tsvector
  GENERATED ALWAYS AS (to_tsvector('jiebacfg', summary)) STORED ;
ALTER TABLE search_index.article ADD COLUMN text_jieba_ts tsvector
  GENERATED ALWAYS AS (to_tsvector('jiebacfg', text_content_converted)) STORED ;
```

need to research if these can be done in program with

```sql
INSERT search_index.article (title_jieba_ts, ...)

to_tsvector( ${PaddleHub lac.cut (title)} )

...
```

**Comment by tx0c** [comment]
and the SQL at search time is:

```sql
FROM search_index.article, plainto_tsquery('jiebacfg', searchKey) query
WHERE
  (query @@ title_jieba_ts OR query @@ summary_jieba_ts OR query @@ text_jieba_ts)`
```

because of no `jiebacfg`, this has to update to something like:

```sql
SELECT ...
FROM search_index.article, to_tsquery(preparedSearchKey) query
WHERE
  (query @@ title_tsv OR query @@ summary_tsv OR query @@ text_tsv)`
```

will not be able to use `plainto_tsquery` but have to parse and prepare the query key:

any search phrase like `南京市长江大桥` will have to be parsed in app to something like `南京市 & 长江 & 大桥`

**Comment by robertu7** [comment]
https://www.notion.so/matterslab/Search-with-in-application-word-segmentation-83c6a9fe3e7742cb9e7238c57f7c4815?pvs=4
