### ISSUE TITLE
Design APIs for Editor and Detail Page

### ISSUE THREAD

**Issue by gary02** [thematters/matters-server#3952]
## Task

- [x] add create/delete/vote journal APIs
- [x] revise `putComment` API
- [x] revise `node` API to return Journal object
- [x] revise `directImageUpload` API

## Story

- https://github.com/thematters/developer-resource/issues/436
- https://github.com/thematters/developer-resource/issues/437

**Comment by gary02** [comment]
https://www.notion.so/matterslab/Journal-2cbdfc47c2de4b9bb3df4e7ae4207ede
