### ISSUE TITLE
Implement APIs for Editor / Detail Page

### ISSUE THREAD

**Issue by gary02** [thematters/matters-server#3953]
## Task

- [x] implement API design in #3952 
- [x] revise `submitReport` api
- [x] revise `node` api
- [x] revise `directImageUpload` api 
- [x] test `node` api
- [x] `putJournal` api ratelimit
- [x] revise `putComment` api

## Story

- https://github.com/thematters/developer-resource/issues/436
- https://github.com/thematters/developer-resource/issues/437
