### ISSUE TITLE
Update notification APIs and logic

### ISSUE THREAD

**Issue by gary02** [thematters/matters-server#3956]
## Task
- [x] update notification setting API
- [x] add / remove notification types
- [x] trigger vote/mention notifications for journal  
- [x] review and revise daily summary email
- [x] delay notification 10s (move notification handling to queue)
- [x] update notification according to [rules](url)
- [ ] cancel delayed notifications

## Story
- https://github.com/thematters/developer-resource/issues/439

## Refs
- https://www.notion.so/matterslab/4bd3ad5700c94504a796c22dae9ba6bc
