### ISSUE TITLE
Server Integration

### ISSUE THREAD

**Issue by gary02** [thematters/matters-server#4079]
### Tasks

- [x] migration to add spam fields in `Article` table
- [x] call Lambda and store spam result
- [x] exclude spam articles in feeds

---
### Story
- https://github.com/thematters/developer-resource/issues/472
