### ISSUE TITLE
Whitelisted domains for new sign up

### ISSUE THREAD

**Issue by zeckli** [thematters/matters-server#4081]
### Todo
- [ ] Historical top *N* domains 
- [ ] Confirm with CC
- [ ] Revise sign up resolver
